server:
  port: 3344
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:blue-toad/springcloud-Config.git # github上面的仓库
          # 注意这里要使用老式秘钥生成方式 生成的老版秘钥
          # 新的秘钥不支持
          search-paths: /**
          # 搜索路径 根目录
          default-label: main
          # 默认分枝

# 访问路径
#          /{app}/{profile}	Configuration data for app in Spring profile (comma-separated).
#          /{app}/{profile}/{label}	Add a git label
#          /{app}/{profile}{label}/{path}	An environment-specific plain text config file (at "path")
# ******测试路径*****
# http://localhost:3344/config-center/application.yml





eureka:
  client:
    register-with-eureka: true #默认为true
    fetch-registry: true #默认为true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
